language: generic 
sudo: required 
services:
  - docker 

before_install: 
  - docker build -t sreehan/react-test -f ./client/Dockerfile.dev ./client 

script: 
  - docker run -e CI=true sreehan/react-test npm test

after_success: 
  - docker build -t sreehan/multi-client ./client 
  - docker build -t sreehan/multi-nginx ./nginx 
  - docker build -t sreehan/multi-server ./server
  - docker build -t sreehan/multi-worker ./worker 
  # Log in to the docker CLI 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub 
  - docker push sreehan/multi-client
  - docker push sreehan/multi-nginx
  - docker push sreehan/multi-server
  - docker push sreehan/multi-worker
