language: generic 
sudo: required 
services:
  - docker 

before_install: 
  - docker build -t sreehan/react-test -f ./client/Dockerfile.dev ./client 

script: 
  - docker run sreehan/react-test npm test -- --coverage 

after_success: 
  - docker build -t sreehan/multi-client ./client 
  - docker build -t sreehan/multi-nginx ./nginx 
  - docker build -t sreehan/multi-server ./server
  - docker build -t sreehan/multi-worker ./worker 